### ISSUE TITLE
improve achievement display

### ISSUE THREAD

**Issue by chriamue** [konnektoren/konnektoren-web-game#24]
# Enhance Achievement Display with Interactive Zoom Effect

## User Story
As a user, I want to be able to click on an achievement to see it in more detail, so that I can better appreciate my accomplishments and read any additional information.

## Acceptance Criteria
- [ ] Implement a zoom-in effect when an achievement is clicked
- [ ] Display additional details about the achievement in the zoomed-in view
- [ ] Add a smooth transition animation for the zoom effect
- [ ] Ensure the zoomed-in view is responsive and looks good on all screen sizes
- [ ] Provide a way to close the zoomed-in view and return to the achievement list

## Technical Notes
- Update the `AchievementComponent` in `achievement.rs` to handle click events
- Create a new `AchievementDetailComponent` for the zoomed-in view
- Use CSS transitions and transforms for the zoom effect
- Implement a modal or overlay for the zoomed-in view
- Ensure accessibility is maintained with keyboard navigation and screen reader support

## Tasks
1. Modify the `AchievementComponent` to add a click handler
3. Implement the zoom-in effect using CSS transitions and transforms
4. Add a backdrop or overlay to focus attention on the zoomed achievement
5. Create a close button or click-outside functionality to exit the zoomed view
6. Update the SCSS in `_achievement.scss` to include styles for the zoom effect and detailed view
7. Ensure the zoom effect and detailed view are responsive across different screen sizes
9. Update the `AchievementsPage` to incorporate the new zoom functionality
10. Write tests for the new interactive features

## Example SCSS Additions
Add the following to `_achievement.scss` (adjust as needed):

```scss
.achievement {
  // ... existing styles ...

  transition: transform 0.3s ease-in-out;
  cursor: pointer;

  &:hover {
    transform: scale(1.05);
  }

  &--zoomed {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%) scale(1.5);
    z-index: 1000;
    background: color("background");
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
    padding: spacing("lg");
    border-radius: border-radius("lg");
    max-width: 90vw;
    max-height: 90vh;
    overflow: auto;
  }
}

.achievement-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 999;
}
```

## Additional Considerations
- Consider adding animations for entering and exiting the zoomed view
- Explore the possibility of adding share functionality for achievements in the zoomed view
- Think about how this interaction might affect the overall layout of the achievements page
